### PR TITLE
Mercenary Content Update

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Icons:
 - Old Nagant icon renamed appropriately.
- - -
Balance:
 - Mercenary Commander now starts with their old rifle once again.
 - Clear Sky Leader now has an appropriate primary.
 - FN F2000S now locked to Mercenaries.
 - Smoke grenades replacing flashbangs.
 - Flashbangs made Mercenary exclusive, with a high price tag and for Experienced and up Stalkers only.
 - SMGs now have their own area in the Sidormat. Prices have been adjusted accordingly.
 - Mercenaries now have access to the following two uniques:
    - FN P90
    - AWSM
- - -
Map:
 - Courtesy of Teragen, Mercenaries now spawn in Garbage, within a special bunker.
- - -

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
Now includes Teragen's changes to Svalka and Rostok.

**Comment by ProbablyCarl** [comment]
fuk u map diffs >:(

**Comment by ProbablyCarl** [comment]
Stuff works. Diff bot is just being crungus.
This is good to merge whenever.

**Comment by emoats18** [comment]
Idiot

**Comment by ProbablyCarl** [comment]
> Idiot

I'm going to take your toes.

**Pull request merged**
